FROM node:16-alpine
# Specifying that the USER which will execute RUN, CMD or
# ENTRYPOINT instructions will be the node user, as opposed 
# to root (default).
USER node
# Creating a directory of /home/node/app prior to the WORKDIR
# instruction. This will prevent a permissions issue since WORKDIR
# by default will create a directory if it does not exist and set
# ownership to root. (We don't want it to be owned by root)
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
# --chown=node:node sets ownership of the files you are copying from
# your local environment to the node user in the container.
COPY --chown=node:node package.json .
RUN npm install
COPY --chown=node:node . .
CMD ["npm", "run", "start"]

